In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1.0, 2.0, 3.0],[2.0, 3.0, 4.0]])

print(a)
print(b)

[1 2 3]
[[1. 2. 3.]
 [2. 3. 4.]]


In [5]:
# Get Dimension

print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get Shape

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [9]:
# Get Size

print(a.itemsize)
print(b.itemsize)

# total size
print(a.size)
print(b.size)

8
8
3
6


In [26]:
# Accessing / Changing specific element

a = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 0, 10, 11, 12, 13, 14]])
#print(a)

# get a specific element(row, col)
print(a[1,6])

# get a specific row
print(a[0,:])

# get a specific col
print(a[:,2])

print(a[0, 1:6:2])
print(a[1, 0:7:2])


14
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[ 8 10 12 14]


## 3D Arrays

In [46]:
b = np.array([[[1, 2],[3, 4]],[[5, 6],[7, 8]]])
print(b.ndim)

# get specific element
print(b[0:1:1])
print(b[:,0,:])
print(b[:,1,:])

#replace values
b[:,1,:] = [[8, 8],[9, 9]]
print(b)


3
[[[1 2]
  [3 4]]]
[[1 2]
 [5 6]]
[[3 4]
 [7 8]]
[[[1 2]
  [8 8]]

 [[5 6]
  [9 9]]]


In [54]:
# Initializing different Types of Arrays

# 1. All zeroes matrix
print(np.zeros((2)))
print(np.zeros((2,3)))


[0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [58]:
# 2. All ones matrix
print(np.ones((2), dtype='int32'))
print(np.ones((4, 2, 2), dtype='int32'))

[1 1]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [65]:
# 3. Any other number
print(np.full((2, 2), 99))

b = np.array([[1.0, 2.0, 3.0],[2.0, 3.0, 4.0]])
print(np.full_like(b, 4))

[[99 99]
 [99 99]]
[[4. 4. 4.]
 [4. 4. 4.]]


In [69]:
## Random numbers
print(np.random.rand(2,2))
print(np.random.randint(7, size=(2,3)))


[[0.87888723 0.48732196]
 [0.6365252  0.77395326]]
[[1 4 5]
 [4 5 5]]


In [70]:
# identity matrix
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [75]:
# repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 4, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [77]:
# Copy an array using assigning

a = np.array([1, 2, 3])
b = a
b[0] = 100
print(a)
print(b)



[100   2   3]
[100   2   3]


In [78]:
# copy an array using copy method

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 99
print(a)
print(b)

[1 2 3]
[99  2  3]


In [88]:
## Linear Algebra
a = np.ones((2, 3))
print(a)
b = np.full((3,2),2)
print(b)
print(np.matmul(a, b))

# find the determinant
c = np.identity(3)
print(np.linalg.det(c))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
1.0


In [95]:
## Statistics

stats = np.array([[1, 2, 3],[4, 5, 6]])
print(stats)
print(np.min(stats, axis = 1))
print(np.min(stats, axis = 0))
print(np.min(stats))
print(np.max(stats))
print(np.sum(stats))

[[1 2 3]
 [4 5 6]]
[1 4]
[1 2 3]
1
6
21


In [104]:
# Reorganizing arrays

before = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
print(before)
print(before.shape)
after = before.reshape(2,4)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [107]:
# Vertically stacking vectors

v1 = np. array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
print(np.vstack([v1, v2]))
print(np.vstack([v1, v2, v2, v1]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [108]:
# Horizontal stack

h1 = np.ones((2,2))
h2 = np.zeros((2,4))
print(np.hstack([h1, h2]))

[[1. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]]


In [110]:
## Iterating 2D Array elements
arr = np.array([[1, 2, 3],[4, 5, 6]])
for i in arr:
    for j in i:
        print(j)

1
2
3
4
5
6


In [112]:
#Iterating array elements using nditer

arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
for n in np.nditer(arr):
    print(n)

1
2
3
4
5
6
7
8
9


In [113]:
## ndenumeratt- to get values along with index

arr = np.array([1, 2, 3, 4])
for index, n in np.ndenumerate(arr):
    print(index, n)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [117]:
## Join Arrays
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])
arr = np.concatenate((arr1, arr2), axis = 1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [118]:
## Split array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

new_arr = np.array_split(arr,2)
print(new_arr)

[array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]]), array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])]


In [121]:
## Search array
# find the indexes where the values are odd

arr = np.array([1,2, 3, 4, 5, 6, 7])
odd = np.where(arr%2==0)
print(odd)

# find the indexes where the values are even
even = np.where(arr%2==1)
print(even)

(array([1, 3, 5]),)
(array([0, 2, 4, 6]),)


In [123]:
## Array sorting

arr = np.array([4,3,2,1])
print(np.sort(arr))

[1 2 3 4]


In [125]:
## Array filter
arr = np.array([40, 41, 42, 43, 45])
filtered_arr = []

for n in arr:
    if n > 41:
        filtered_arr.append(True)
    else:
        filtered_arr.append(False)

new_arr = arr[filtered_arr]       
print(new_arr)
print(filtered_arr)


[42 43 45]
[False, False, True, True, True]


In [126]:
# create a filter array that will return only even numbers
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filtered_arr = arr%2 == 0
new_arr = arr[filtered_arr]
print(new_arr)
print(filtered_arr)

[2 4 6]
[False  True False  True False  True False]
